from __future__ import annotations

from typing import Protocol, runtime_checkable

from ..domain.models import Annotation, Annotator, Item, Project, Task, Unit


@runtime_checkable
class ProjectStore(Protocol):
    """プロジェクト1件分の永続化の抽象。

    SQLite実装（storage/sqlite.py）がこれを満たす。将来の複数人対応では
    RDB実装を追加し、servicesへの注入だけを差し替える。
    """

    def add_project(self, p: Project) -> None: ...
    def get_project(self) -> Project: ...
    def add_items(self, items: list[Item]) -> None: ...
    def list_items(self, project_id: str) -> list[Item]: ...
    def add_task(self, t: Task) -> None: ...
    def get_task(self, task_id: str) -> Task: ...
    def list_tasks(self, project_id: str) -> list[Task]: ...
    def add_units(self, units: list[Unit]) -> None: ...
    def list_units(self, task_id: str) -> list[Unit]: ...
    def get_default_annotator(self) -> Annotator: ...
    def save_annotation(self, a: Annotation) -> None: ...
    def list_annotations_for_task(self, task_id: str) -> list[Annotation]: ...
    def close(self) -> None: ...
